### ISSUE TITLE
UVR-MDX-NET-Inst_1.onnx and UVR-MDX-NET-Inst_HQ_3.onnx got error

### ISSUE THREAD

**Issue by z6m8n7ljw** [seanghay/uvr-mdx-infer#6]
`UVR-MDX-NET-Inst_Main.onnx` works well, but `UVR-MDX-NET-Inst_1.onnx` and `UVR-MDX-NET-Inst_HQ_3.onnx` got error:
`onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: input for the following indices
 index: 2 Got: 2048 Expected: 3072
 Please fix either the inputs/outputs or the model.`

**Comment by seanghay** [comment]
@z6m8n7ljw  try adding `-f 3072`

**Comment by z6m8n7ljw** [comment]
> @z6m8n7ljw try adding `-f 3072`

Thx~ It works. So the `dimensions for input` corresponds to `dim_f`.

**Comment by z6m8n7ljw** [comment]
> @z6m8n7ljw try adding `-f 3072`

Thx~ It works. So the `dimensions for input` corresponds to `dim_f`.
