### ISSUE TITLE
Output specified vocal/inst track only

### ISSUE THREAD

**Issue by z6m8n7ljw** [seanghay/uvr-mdx-infer#7]
I found `target_name="vocals"` in model initialization, but the direct output of `predict()` is actually the inst track (?)
```
sources = self.demix(mix.T)
opt = sources[0].T

return (mix - opt, opt, rate)
```
How come? And how to output a track based on the specified `target_name`.

**Comment by seanghay** [comment]
I think the parameter you mentioned is unused. The source separation output is based on specified model and it can be vary. So think of it as `source-1.wav` and `source-2.wav`
